from src.core.application_server.routes.utils import init as init_utils_routes
from src.core.application_server.routes.configure import init as init_configure_routes
from src.core.application_server.routes.start import init as init_start_routes
from src.core.application_server.routes.stop import init as init_stop_routes
from src.core.application_server.routes.restart import init as init_restart_routes
from src.core.application_server.routes.deploy import init as init_deploy_routes
from src.core.application_server.routes.set import init as init_set_routes
from src.core.application_server.routes.drop import init as init_drop_routes
from src.core.application_server.routes.list import init as init_list_routes
from src.core.application_server.routes.schedule import init as init_schedule_routes
from src.core.application_server.routes.update import init as init_update_routes
from src.core.application_server.routes.backup import init as init_backup_routes
